print("PYTHON")
print("Introduction:")
print("This assignment is based on the summary of the day-2 class in the Letsupgrade.We learnt about Basic syntax ,Python variables and assignments and types of operators.")
print("BASIC SYNTAX:")
print("In basic syntax we learnt about Backslash,Triple quotes,String inside the quote,Escape sequence and Formatted output. ")
print("PYTHON VARIABLES AND ASSIGNMENT STATEMENTS:")
print("Variables means linking of data with name.We also learnt some rules to define a varaible.Then we saw about  python assignment statement")
print("TYPES OF OPERATORS:")
print("There are seven types of operators.They are:Arithmetic operator,Comparison operators,Assignment operators,Bitwise operator,Logical operator,Membership operator and Identity operator")
print("CONCLUSION:")
print("These were the things thought in the day-2 class.It was very interesting to learn.....")